### ISSUE TITLE
Are there any plans to update to the latest version of Nuxt?

### ISSUE THREAD

**Issue by Heunsig** [alexdeploy/developer-portfolio-v2#25]
First of all, your work is amazing. However, I am using Node 20, and your portfolio template is not compatible with it. Do you have any plans to update to the latest version of Nuxt (currently v3.13)?

**Comment by alexdeploy** [comment]
Hi @Heunsig, Thanks!

I have a few updates planned for the project in the coming weeks, and I'll be taking the opportunity to migrate from Node 18 to Node 20 during that time. I've already opened an issue to track the progress of the update, which you can follow here: [Update project for Node.js 20 compatibility](https://github.com/alexdeploy/developer-portfolio-v2/issues/26).

Feel free to take the challenge ;)

**Comment by Heunsig** [comment]
@alexdeploy That sounds great! I’m looking forward to seeing the upgraded version of your work, and I’m closing this issue.
